---
hosts:
  haproxy-test1:
    ip: 192.168.30.10
    memory: 512
  haproxy-test2:
    ip: 192.168.30.11
    memory: 512
  supercool-app-test1:
    ip: 192.168.30.20
    memory: 256
  supercool-app-test2:
    ip: 192.168.30.21
    memory: 256
